### ISSUE TITLE
Script singelplayer

### ISSUE THREAD

**Issue by alberto28099** [TheCyberQuake/ServerHack#1]
Sorry I could do the same script but to run when entering with singelplayer or unblock the multiplayer tab I want it to connect to this server

https://www.spigotmc.org/resources/%E3%80%90dragonproxy%E3%80%91-%E2%80%94%E2%80%94-join-any-pc-server-using-mcpe-mcwin10.49610/updates

**Comment by alberto28099** [comment]
i have nintendo switch lite

**Comment by TheCyberQuake** [comment]
> 
> 
> Sorry I could do the same script but to run when entering with singelplayer or unblock the multiplayer tab I want it to connect to this server
> 
> https://www.spigotmc.org/resources/%E3%80%90dragonproxy%E3%80%91-%E2%80%94%E2%80%94-join-any-pc-server-using-mcpe-mcwin10.49610/updates

Unfortunately that is completely impossible due to the nature of how this method works. This script doesn't do any kind of modification to anything on the console or the game, it merely intercepts traffic coming from the game to the network, and then redirects that traffic from one of the pre-determined servers to instead point to our own servers.
In order to accomplish what you want, you would need to mod the game, which in turn would require hacking the Nintendo Switch. And for the Switch Lite, the only exploits known involve opening the system up and soldering inside it. Not to mention exploiting the Switch in any capacity that would allow something like this would ultimately get your console banned anyway.

As for running with DragonProxy in order to connect to a Java server from the bedrock versions, it seems DragonProxy is no longer supported, but the project at https://geysermc.org/ has replaced it. In theory you should be able to run that program, and then on the same computer, run my script and for the server use 127.0.0.1:19132
Doing that along with following my directions would in theory have my script redirect from your Switch to it, then from it to GeyserMC, and from there to whatever Java edition server you set in GeyserMC to connect to.

**Comment by alberto28099** [comment]
thanks
